### ISSUE TITLE
Update clippy config to include perf, suspicious, style, and complexity lint groups

### ISSUE THREAD

**Issue by l-monninger** [movementlabsxyz/M1#8]
In the interest of the intended code quality, include `::perf`, `::suspicious`, `::style`, and `::complexity`.

```toml
[lint]
lint-groups = ["suspicious", "perf", "style", "complexity"]
```

Further modulation to be addressed in the comments below.
